import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {Providers} from '@/app/lib/Components/Providers'
import {Navbar} from "@/app/lib/Components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Navbar />
          <hr />
          {children}
        </Providers>
      </body>
    </html>
  );
}
